# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LtvbNGZYIZEw1-1Axx_CbQvqf6zCYJhV
"""

import numpy

menu = 0
i = 0
lista_nombre=[]
lista_edad=[]
lista_nif=[]

while menu == 0:
  print("MENU")
  print("-----------------")
  print("1- Registrar nuevo NIF")
  print("2- Buscar por NIF")
  print("3- Imprimir certificados")
  print("4- Salir del programa")
  op_menu = int(input("Ingrese su opcion: "))
  if op_menu == 1:
    print("1. Registrar un NIF")
    print("-----------------")
    nif = input("Ingrese NIF a registrar: ")
    if len(nif) != 12:
      print("Ingrese NIF valido, volviendo al menu.")
    else:
      nombre = input("Ingrese nombre a registrar: ")
      if len(nombre) < 8:
        print("El nombre debe tener minimo 8 caracteres, volviendo al menu.")
      else:
        try:
          edad = int(input("Ingrese edad: "))
          if edad < -1:
            print("Ingrese edad valida, volviendo al menu.")
          else:
            lista_nombre.append(nombre)
            lista_edad.append(edad)
            lista_nif.append(nif)
            print("NIF creado exitosamente, volviendo al menu.")
        except:
          print("Ingrese edad valida, volviendo al menu.")
  elif op_menu == 2:
    print("2. Buscar por NIF")
    print("-----------------")
    nif = input("Ingrese NIF a buscar: ")
    for i in range (len(lista_nif)):
      if lista_nif[i] == nif:
        print("Su NIF es:", lista_nif[i])
        print("Su nombre es:", lista_nombre[i])
        print("Su edad es:", lista_edad[i])
        print("Pertenece a la Union  Europea")
      else:
        print("NIF no encontrado, volviendo al menu.")
  elif op_menu == 3:
    print("3. Certificados")
    print("-----------------")
  elif op_menu == 4:
    print("4. Saliendo del menu...")
    print("-----------------")
    print("Programa hecho por Benjamin Barria, version 1.0.")
    menu = 1